-- PUBLIC.PRODUCT definition

-- Drop table

-- DROP TABLE PUBLIC.PRODUCT;

CREATE TABLE PUBLIC.PRODUCT (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	CODE VARCHAR(20) NOT NULL,
	VALUE DOUBLE DEFAULT 0.00 NOT NULL,
	`TYPE` VARCHAR(100) NOT NULL,
	IMAGE BINARY,
	CONSTRAINT PRODUCT_PK PRIMARY KEY (ID)
);