-- Drop table

DROP TABLE PUBLIC."USER";

CREATE TABLE PUBLIC."USER" (
	ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	AGE INTEGER NOT NULL,
	REGISTRATION BIGINT NOT NULL,
	DOCUMENT VARCHAR(11) NOT NULL,
	PASSWORD VARCHAR(8) NOT NULL,
	CONSTRAINT USER_PK PRIMARY KEY (ID)
);

INSERT INTO PUBLIC."USER" (NAME, AGE, REGISTRATION, DOCUMENT, PASSWORD) VALUES('ADMIN', 99, 1, 12345678910, '12345678');

